In [1]:
import pandas as pd
import numpy as np

In [5]:
sf_crime = pd.read_csv("../clean_data/sf_crime.csv")
sf_crime = sf_crime.drop(["Unnamed: 0"], axis = 1)
sf_crime

,city,population,violent crime,murder and nonnegligent manslaughter,rape,robbery,aggravated assault,property crime,burglary,larceny-theft,motor vehicle theft,arson,state,year,violent_rate,property_rate,total_rate
0,San Francisco,764693.0,5323.0,55.0,308.0,2371.0,2589.0,47759.0,5947.0,35530.0,6282.0,344.0,California,2022,0.006961,0.062455,0.069416
1,San Francisco,881514.0,4796.0,48.0,198.0,2388.0,2162.0,38737.0,7452.0,25319.0,5966.0,377.0,California,2020,0.005441,0.043944,0.049384
2,San Francisco,886007.0,5933.0,40.0,324.0,3055.0,2514.0,48780.0,4644.0,39887.0,4249.0,275.0,California,2019,0.006696,0.055056,0.061752
3,San Francisco,889282.0,6144.0,46.0,354.0,3165.0,2579.0,49214.0,5322.0,39675.0,4217.0,288.0,California,2018,0.006909,0.055341,0.062250
4,San Francisco,881255.0,6301.0,56.0,367.0,3220.0,2658.0,54356.0,4935.0,44587.0,4834.0,303.0,California,2017,0.007150,0.061680,0.068830
5,San Francisco,871155.0,6190.0,57.0,342.0,3175.0,2616.0,47402.0,4978.0,36991.0,5433.0,255.0,California,2016,0.007106,0.054413,0.061518
6,San Francisco,863782.0,6710.0,53.0,344.0,3610.0,2703.0,53019.0,5186.0,40918.0,6915.0,272.0,California,2015,0.007768,0.061380,0.069148
7,San Francisco,850294.0,6761.0,45.0,355.0,3224.0,3137.0,45093.0,5237.0,33730.0,6126.0,241.0,California,2014,0.007951,0.053032,0.060984
8,San Francisco,833863.0,7064.0,48.0,161.0,4202.0,2653.0,48324.0,5931.0,36527.0,5866.0,227.0,California,2013,0.008471,0.057952,0.066423
9,San Francisco,820363.0,5777.0,69.0,108.0,3484.0,2116.0,38898.0,5317.0,28242.0,5339.0,207.0,California,2012,0.007042,0.047416,0.054458
10,San Francisco,814701.0,5374.0,50.0,131.0,3088.0,2105.0,32886.0,4408.0,24304.0,4174.0,161.0,California,2011,0.006596,0.040366,0.046962
11,San Francisco,818594.0,5747.0,48.0,133.0,3180.0,2386.0,32365.0,4557.0,23905.0,3903.0,156.0,California,2010,0.007021,0.039537,0.046558
12,San Francisco,809755.0,5957.0,45.0,179.0,3423.0,2310.0,34509.0,5197.0,24399.0,4913.0,198.0,California,2009,0.007357,0.042617,0.049973
13,San Francisco,798144.0,6744.0,98.0,166.0,4108.0,2372.0,36301.0,5401.0,25142.0,5758.0,235.0,California,2008,0.008450,0.045482,0.053931
14,San Francisco,733799.0,6414.0,100.0,125.0,3771.0,2418.0,34456.0,5079.0,23474.0,5903.0,232.0,California,2007,0.008741,0.046956,0.055696
15,San Francisco,746085.0,6533.0,86.0,154.0,3858.0,2435.0,36992.0,6465.0,23891.0,6636.0,226.0,California,2006,0.008756,0.049581,0.058338
16,San Francisco,749172.0,5985.0,96.0,172.0,3078.0,2639.0,34269.0,6208.0,19887.0,8174.0,188.0,California,2005,0.007989,0.045742,0.053731
17,San Francisco,760353.0,5757.0,88.0,152.0,3041.0,2476.0,35869.0,6097.0,21711.0,8061.0,258.0,California,2004,0.007571,0.047174,0.054746
18,San Francisco,772065.0,5725.0,69.0,215.0,3065.0,2376.0,38163.0,5784.0,25388.0,6991.0,260.0,California,2003,0.007415,0.049430,0.056845

In [9]:
unemployment_df = pd.read_csv("../clean_data/sf_unemployment.csv")
unemployment_df = unemployment_df.drop(["Unnamed: 0"], axis = 1)
unemployment_df

    year  unemployment average
0   2003          29184.416667
1   2004          24197.416667
2   2005          20554.416667
3   2006          17462.666667
4   2007          18189.416667
5   2008          24093.333333
6   2009          41801.583333
7   2010          44207.750000
8   2011          40366.250000
9   2012          34978.333333
10  2013          28430.250000
11  2014          23335.666667
12  2015          19844.500000
13  2016          18344.416667
14  2017          16606.000000
15  2018          13639.416667
16  2019          12865.083333
17  2020          44465.583333
18  2021          27827.083333
19  2022          14599.833333